/**
 * The README's table of cross-app actions, generated from package.json's
 * `conjureos.actions` so the two can't drift apart (a test checks they
 * match).
 *
 *   npm run docs:actions     rewrite the table in README.md
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

export const START = "<!-- actions:start (generated by npm run docs:actions; do not edit) -->";
export const END = "<!-- actions:end -->";

/** `logFood({ name, calories?, meal? })` — required params plain, optional with `?`. */
function signature(name, action) {
  const props = Object.keys(action.params?.properties ?? {});
  const required = new Set(action.params?.required ?? []);
  const args = props.map((p) => (required.has(p) ? p : `${p}?`));
  return `${name}(${args.length ? `{ ${args.join(", ")} }` : ""})`;
}

/** The description's first sentence: what the action does, for a table cell.
 *  Sentences here often start with a lowercase param name ("items is 1-20
 *  foods"), so any sentence end counts except "e.g." and "i.e.". */
function firstSentence(text) {
  const clean = (s) => s.replace(/\s+/g, " ").replace(/\|/g, "\\|");
  const end = /[.!?](?=\s)/g;
  for (let m = end.exec(text); m; m = end.exec(text)) {
    if (/(e\.g|i\.e)\.$/i.test(text.slice(Math.max(0, m.index - 4), m.index + 1))) continue;
    return clean(text.slice(0, m.index + 1));
  }
  return clean(text);
}

/** The generated block, markers included. */
export function renderActionsTable(pkg) {
  const rows = Object.entries(pkg.conjureos.actions).map(
    ([name, a]) =>
      `| \`${signature(name, a)}\` | ${a.permission === "actions.write" ? "write" : "read"} | ${firstSentence(a.description)} |`,
  );
  return [START, "| Action | Kind | What it does |", "|---|---|---|", ...rows, END].join("\n");
}

/** README with its block replaced by a freshly generated one. */
export function withTable(readme, pkg) {
  const start = readme.indexOf(START);
  const end = readme.indexOf(END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error("README.md is missing the actions:start / actions:end markers");
  }
  return readme.slice(0, start) + renderActionsTable(pkg) + readme.slice(end + END.length);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const root = new URL("..", import.meta.url);
  const pkg = JSON.parse(readFileSync(new URL("package.json", root), "utf8"));
  const path = new URL("README.md", root);
  writeFileSync(path, withTable(readFileSync(path, "utf8"), pkg));
  console.log(`README.md: ${Object.keys(pkg.conjureos.actions).length} actions`);
}
